### PR TITLE
CreateProplistParameter

### LINKED ISSUE #56: Can't use .proplist
I am having trouble using the `.proplist` command parameter.

Allowing it to automatically detect the `TikCommandParameterFormat` seem, to make it fail and not return anything at all.

Example code:
``` C#
ITikCommand cmd = conn.CreateCommand("/ip/address/print"
                                    ,conn.CreateParameter(".proplist", "address")
                                    ,conn.CreateParameter("interface", "bridge", TikCommandParameterFormat.Filter)
                                    ,conn.CreateParameter("disabled", "no", TikCommandParameterFormat.Filter)
                                    );
ITikSentence address = cmd.ExecuteSingleRow();
```

Nothing is returned at all.

-----

I have dug into the source code a little to see why it isn't read correctly, and I think I have to set `parameterFormat` to `TikCommandParameterFormat.Tag`. But it doesn't work as I expected.

Example code:
``` C#
ITikCommand cmd = conn.CreateCommand("/ip/address/print"
                                    ,conn.CreateParameter(".proplist", "address", TikCommandParameterFormat.Tag)
                                    ,conn.CreateParameter("interface", "bridge", TikCommandParameterFormat.Filter)
                                    ,conn.CreateParameter("disabled", "no", TikCommandParameterFormat.Filter)
                                    );
ITikSentence address = cmd.ExecuteSingleRow();
```

I am expecting only to get the `address` word, but I am still getting all the other properties from the router.

-----

My old [pure API](https://wiki.mikrotik.com/wiki/API_in_C_Sharp) program has it working fine like this:
``` C#
_mikrotik.Send("/ip/address/print");
_mikrotik.Send("=.proplist=address");
_mikrotik.Send("?interface=bridge");
_mikrotik.Send("?disabled=no", true);
foreach (string h in _mikrotik.Read())
```

### PR DESCRIPTION
**Pull request by Deantwo**
Implemented a shortcut for creating a ".proplist" command parameter.

I didn't test it yet, but it looks simple enough that it should work.

Thoughts? Feedback?

Fixes #56

### CODE REVIEW

**Comment by Deantwo** [comment]
Usage example:
``` C#
ITikCommand cmd = conn.CreateCommand("/ip/dhcp-server/lease/print"
                                    ,conn.CreateProplistParameter("address", "mac-address", "status", "expires-after", "host-name", "dynamic")
                                    ,conn.CreateParameter("?server","my_dhcp")
                                    ,conn.CreateParameter("?disabled","no")
                                    );
IEnumerable<ITikSentence> list = cmd.ExecuteList();
```

**Comment by Deantwo** [comment]
Usage example:
``` C#
ITikCommand cmd = conn.CreateCommand("/ip/dhcp-server/lease/print");
cmd.AddProplistParameter(".id", "address", "mac-address", "status", "expires-after", "host-name", "dynamic")
cmd.AddCreateParameter("server","my_dhcp", TikCommandParameterFormat.Filter)
cmd.AddCreateParameter("disabled","no", TikCommandParameterFormat.Filter)
IEnumerable<ITikSentence> list = cmd.ExecuteList();
```

**Comment by Deantwo** [comment]
Sure? I am not even sure what _extension / builder method_ is, maybe more advanced than what I am used to.

**Comment by danikf** [comment]
Hi - hope you will accept this solution :-)
Thanks for ideas and code!
D

**Comment by Deantwo** [comment]
I didn't expect my code to be prefect. Just use the base ideas as you think they work best in your project.

**Pull request merged**
